const CONSTANTS = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT: 'LOGOUT',
  THEMES_REQUEST: 'THEMES_REQUEST',
  THEMES_SUCCESS: 'THEMES_SUCCESS',
  THEMES_ERROR: 'THEMES_ERROR',
  SPECIFIC_THEME_OBJ_REQUEST: 'SPECIFIC_THEME_OBJ_REQUEST',
  SPECIFIC_THEME_OBJ_SUCCESS: 'SPECIFIC_THEME_OBJ_SUCCESS',
  SPECIFIC_THEME_OBJ_ERROR: 'SPECIFIC_THEME_OBJ_ERROR',
  REVIEWS_REQUEST: 'REVIEWS_REQUEST',
  REVIEWS_SUCCESS: 'REVIEWS_SUCCESS',
  REVIEWS_ERROR: 'REVIEWS_ERROR',
  DEFAULTS: {
    THEME_LIMIT: 20,
    REVIEW_LIMIT: 20,
  },
  MESSAGES: {
    NOTHING_FOUND: 'Sorry, but nothing was found according to your request',
    PAGE_NOT_FOUND: 'Sorry, the page you requested was not found',
    WENT_WRONG: 'Sorry, something went wrong, but we are already working on it',
  },
};

export default CONSTANTS;
